/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;

/**
 *
 * @author Hangeyes
 */
public class AddTab extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form TabbedMenu2
     */
    public AddTab() {
        initComponents();
        phylumRadioButton.addActionListener(this);
        familyRadioButton.addActionListener(this);
        speciesRadioButton.addActionListener(this);
    }
    
     public String getCheckedRadioButton()
    {
        if(phylumRadioButton.isSelected())
        {
            return "phylum";
        }
        if(familyRadioButton.isSelected())
        {
            return "family";
        }
        if(speciesRadioButton.isSelected())
        {
            return "species";
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        phylumNameCB = new javax.swing.JComboBox();
        familyNameCB = new javax.swing.JComboBox();
        phylumPopulationTextField = new javax.swing.JTextField();
        phylumAnatomyTextField = new javax.swing.JTextField();
        familyCharacteristicTextField = new javax.swing.JTextField();
        familyAverageLimbCountTextField = new javax.swing.JTextField();
        speciesNameTextField = new javax.swing.JTextField();
        speciesDiscoveryDateTextField = new javax.swing.JTextField();
        speciesRepresentantTextField = new javax.swing.JTextField();
        speciesLimbCountTextField = new javax.swing.JTextField();
        speciesName1CB = new javax.swing.JComboBox();
        speciesName2CB = new javax.swing.JComboBox();
        phylumRadioButton = new javax.swing.JRadioButton();
        familyRadioButton = new javax.swing.JRadioButton();
        speciesRadioButton = new javax.swing.JRadioButton();
        phylumNameTextField = new javax.swing.JTextField();
        familyNameTextField = new javax.swing.JTextField();
        speciesNameCB = new javax.swing.JComboBox();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        addButton.setText("Dodaj wpis");

        phylumNameCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        familyNameCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        phylumPopulationTextField.setText("Populacja");

        phylumAnatomyTextField.setText("Budowa");

        familyCharacteristicTextField.setText("Cecha charakterystyczna");

        familyAverageLimbCountTextField.setText("Średnia ilość kończyn");

        speciesNameTextField.setText("Nazwa");

        speciesDiscoveryDateTextField.setText("Data odkrycia");

        speciesRepresentantTextField.setText("Przedstawiciel");

        speciesLimbCountTextField.setText("Ilość kończyn");

        speciesName1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        speciesName2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        phylumRadioButton.setText("Typ:");

        familyRadioButton.setText("Rodzina:");

        speciesRadioButton.setText("Gatunek:");

        phylumNameTextField.setText("Nazwa");

        familyNameTextField.setText("Nazwa");

        speciesNameCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        editButton.setText("Edytuj");

        deleteButton.setText("Usuń");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phylumRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(familyRadioButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(familyNameCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phylumNameCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(speciesRadioButton)
                                .addGap(24, 24, 24)
                                .addComponent(speciesNameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(familyNameTextField)
                            .addComponent(speciesDiscoveryDateTextField)
                            .addComponent(phylumNameTextField)
                            .addComponent(speciesNameTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(phylumPopulationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phylumAnatomyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(familyCharacteristicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(familyAverageLimbCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(speciesLimbCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speciesName1CB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(speciesName2CB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(speciesRepresentantTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phylumNameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phylumRadioButton)
                    .addComponent(phylumNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phylumPopulationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phylumAnatomyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(familyNameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familyAverageLimbCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familyRadioButton)
                    .addComponent(familyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familyCharacteristicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speciesNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesName1CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesRadioButton)
                    .addComponent(speciesName2CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesNameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speciesDiscoveryDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesLimbCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesRepresentantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton addButton;
    javax.swing.JButton deleteButton;
    javax.swing.JButton editButton;
    javax.swing.JTextField familyAverageLimbCountTextField;
    javax.swing.JTextField familyCharacteristicTextField;
    javax.swing.JComboBox familyNameCB;
    javax.swing.JTextField familyNameTextField;
    private javax.swing.JRadioButton familyRadioButton;
    javax.swing.JTextField phylumAnatomyTextField;
    javax.swing.JComboBox phylumNameCB;
    javax.swing.JTextField phylumNameTextField;
    javax.swing.JTextField phylumPopulationTextField;
    private javax.swing.JRadioButton phylumRadioButton;
    javax.swing.JTextField speciesDiscoveryDateTextField;
    javax.swing.JTextField speciesLimbCountTextField;
    javax.swing.JComboBox speciesName1CB;
    javax.swing.JComboBox speciesName2CB;
    javax.swing.JComboBox speciesNameCB;
    javax.swing.JTextField speciesNameTextField;
    private javax.swing.JRadioButton speciesRadioButton;
    javax.swing.JTextField speciesRepresentantTextField;
    // End of variables declaration//GEN-END:variables

    
    /*class RadioButtonListener implements ActionListener
    {
        void RadioButtonListener()
        {
            phylumRadioButton.addActionListener(this);
            familyRadioButton.addActionListener(this);
            speciesRadioButton.addActionListener(this);
            
        }*/
        @Override
        public void actionPerformed(ActionEvent e) {
            Object source = e.getSource();
            if (source == phylumRadioButton)
            {
                phylumRadioButton.setSelected(true);
                phylumNameCB.setVisible(true);
                phylumAnatomyTextField.setVisible(true);
                phylumNameTextField.setVisible(true);
                phylumPopulationTextField.setVisible(true);
                
                familyRadioButton.setSelected(false);
                familyAverageLimbCountTextField.setVisible(false);
                familyCharacteristicTextField.setVisible(false);
                familyNameCB.setVisible(false);
                familyNameTextField.setVisible(false);
                
                speciesRadioButton.setSelected(false);
                speciesDiscoveryDateTextField.setVisible(false);
                speciesLimbCountTextField.setVisible(false);
                speciesNameCB.setVisible(false);
                speciesName1CB.setVisible(false);
                speciesName2CB.setVisible(false);
                speciesNameTextField.setVisible(false);
                speciesRepresentantTextField.setVisible(false);
                
                
            } else if(source == familyRadioButton)
            {
                phylumRadioButton.setSelected(false);
                phylumNameCB.setVisible(true);
                phylumAnatomyTextField.setVisible(false);
                phylumNameTextField.setVisible(false);
                phylumPopulationTextField.setVisible(false);
                
                familyRadioButton.setSelected(true);
                familyAverageLimbCountTextField.setVisible(true);
                familyCharacteristicTextField.setVisible(true);
                familyNameCB.setVisible(true);
                familyNameTextField.setVisible(true);
                
                speciesRadioButton.setSelected(false);
                speciesDiscoveryDateTextField.setVisible(false);
                speciesLimbCountTextField.setVisible(false);
                speciesNameCB.setVisible(false);
                speciesName1CB.setVisible(false);
                speciesName2CB.setVisible(false);
                speciesNameTextField.setVisible(false);
                speciesRepresentantTextField.setVisible(false);
                
                
            } else if (source == speciesRadioButton)
            {
                phylumRadioButton.setSelected(false);
                phylumNameCB.setVisible(false);
                phylumAnatomyTextField.setVisible(false);
                phylumNameTextField.setVisible(false);
                phylumPopulationTextField.setVisible(false);
                
                familyRadioButton.setSelected(false);
                familyAverageLimbCountTextField.setVisible(false);
                familyCharacteristicTextField.setVisible(false);
                familyNameCB.setVisible(true);
                familyNameTextField.setVisible(false);
                
                speciesRadioButton.setSelected(true);
                speciesDiscoveryDateTextField.setVisible(true);
                speciesLimbCountTextField.setVisible(true);
                speciesNameCB.setVisible(true);
                speciesName1CB.setVisible(true);
                speciesName2CB.setVisible(true);
                speciesNameTextField.setVisible(true);
                speciesRepresentantTextField.setVisible(true);
            } else
            {
                System.out.print("Event source not recoginized");
            }
                    
        }
    //}

    
}
